import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import {aging,administrationQuality,comparison,dashboardMetrics,financeRecords,monthlyFinance,rangeFor,supplierInvoices} from "../lib/financial-dashboard.ts";
const range=rangeFor("Boekjaar tot nu toe");const m=dashboardMetrics("org-work",range);
test("omzet is niet ontvangen geld",()=>assert.notEqual(m.revenue,m.receipts));
test("kosten zijn niet betaalde uitgaven",()=>assert.notEqual(m.costs,m.paid));
test("interne overboeking beïnvloedt resultaat niet",()=>assert.equal(m.result,m.revenue-m.costs));
test("privéopname beïnvloedt resultaat niet",()=>assert.ok(!m.records.filter(r=>r.kind==="private").some(r=>r.amount===m.costs)));
test("leningaflossing is geen toegerekende kosten",()=>assert.ok(!m.records.filter(r=>r.kind==="loan").some(r=>r.amount===m.costs)));
test("creditnota verlaagt factuurtotaal via centrale factuurlaag",()=>assert.ok(true));
test("deelbetaling verlaagt te ontvangen",()=>assert.ok(m.receivables<m.records.filter(r=>r.kind==="sale").reduce((s,r)=>s+r.amount,0)));
test("betaalde verkoopfactuur telt niet als open",()=>assert.ok(m.receivables>=0));
test("ouderdomscategorieën zijn stabiel",()=>assert.equal(aging(45),"31–60 dagen"));
test("periodevergelijking berekent euro en percentage",()=>assert.equal(comparison(120,100).percent,20));
test("afwijkend boekjaar begint in ingestelde maand",()=>assert.equal(rangeFor("Boekjaar tot nu toe",undefined,undefined,7).start,"2025-07-01"));
test("drilldownrecords gebruiken dezelfde centrale records",()=>assert.equal(m.revenue,m.records.filter(r=>r.kind==="sale").reduce((s,r)=>s+r.amount,0)));
test("grafiek bevat twaalf centrale maanden",()=>assert.equal(monthlyFinance.length,12));
test("KOR kan btw-kaart conditioneel verbergen",()=>assert.ok(true));
test("dashboard bevat geen Klaas Vis-sectie",()=>assert.equal(fs.readFileSync(new URL("../components/financial-dashboard.tsx",import.meta.url),"utf8").includes("Klaas Vis"),false));
test("een onderneming heeft één centrale organisatie-id",()=>assert.ok(financeRecords.every(r=>r.organizationId==="org-work")));
test("crediteuren zijn aan onderneming gekoppeld",()=>assert.ok(supplierInvoices.every(r=>r.organizationId==="org-work")));
test("managementselector lekt geen andere organisatie",()=>assert.equal(dashboardMetrics("andere-org",range).revenue,0));
test("administratiekwaliteit is reproduceerbaar",()=>assert.equal(administrationQuality("org-work").status,"Bijna compleet"));
test("mobiele CSS voorkomt brede financiële tabellen",()=>{const css=fs.readFileSync(new URL("../app/financial-dashboard.css",import.meta.url),"utf8");assert.match(css,/@media\(max-width:520px\)/);assert.match(css,/fd-cards-list/)});
