import test from "node:test";
import assert from "node:assert/strict";
import { can } from "../lib/access.ts";
import { users } from "../lib/seed.ts";
import { canAccessInsuranceDocument, changeRequests, claims, generalInsuranceEmail, insuranceConversations, insuranceDocuments, insuranceRelationships, isInsuranceModuleVisible, officeInsuranceSignals, policies, policiesForUser, relationshipForOrganization, validateInsuranceUpload } from "../lib/insurance.ts";

test("module is verborgen wanneer niet van toepassing", () => assert.equal(isInsuranceModuleVisible("user-randy", "org-onbekend"), false));
test("module wordt zichtbaar na gecontroleerde activering", () => assert.equal(isInsuranceModuleVisible("user-randy", "org-work"), true));
test("particuliere en zakelijke polissen hebben afzonderlijke koppelingen", () => assert.ok(policies.every(p => Boolean(p.organizationId) !== Boolean(p.personalUserId))));
test("medewerker krijgt geen wijzigings- of schaderecht via financiële rol", () => { assert.equal(can("user-ed", "org-work", "insurance-change:submit"), false); assert.equal(can("user-ed", "org-work", "claim:submit"), false); });
test("gebruiker ziet uitsluitend polissen van toegewezen onderneming", () => assert.ok(policiesForUser("user-ed", "org-work").every(p => p.organizationId === "org-work")));
test("polisdocumenten vereisen servercontrole", () => { assert.equal(canAccessInsuranceDocument("user-ed", "ins-doc-1"), true); assert.equal(canAccessInsuranceDocument("user-blocked", "ins-doc-1"), false); });
test("gemanipuleerd document-id wordt geweigerd", () => assert.equal(canAccessInsuranceDocument("user-randy", "ins-doc-onbekend"), false));
test("gemanipuleerd polis-id behoort niet tot de zichtbare lijst", () => assert.equal(policiesForUser("user-randy", "org-work").some(p => p.id === "policy-onbekend"), false));
test("wijzigingsverzoek verandert polis niet automatisch", () => { const request = changeRequests[0]; assert.notEqual(request.status, "Bevestigd"); assert.equal(policies.find(p => p.id === request.policyId)?.status, "Wijziging in behandeling"); });
test("schademelding bevestigt nooit automatisch dekking", () => assert.ok(claims.every(c => !["Akkoord", "Uitkering volgt"].includes(c.status))));
test("uploads worden op type en grootte gevalideerd", () => { assert.equal(validateInsuranceUpload({ type: "application/pdf", size: 1500 }), true); assert.equal(validateInsuranceUpload({ type: "text/html", size: 1500 }), false); assert.equal(validateInsuranceUpload({ type: "image/jpeg", size: 11_000_000 }), false); });
test("algemene e-mail bevat geen polis- of schadegegevens", () => { assert.equal(generalInsuranceEmail, "Er staat een nieuw bericht over uw verzekering voor u klaar."); assert.doesNotMatch(generalInsuranceEmail, /polis|schade|medisch/i); });
test("verzoek bevat een klantveilige tijdlijn", () => assert.ok(changeRequests[0].timeline.length >= 2));
test("Klaas Vis-reactie verschijnt in portaal", () => assert.ok(insuranceConversations.some(c => c.messages.some(m => m.sender === "Klaas Vis"))));
test("Destination Known Office ziet alleen administratieve signalen", () => assert.ok(officeInsuranceSignals("org-work").every(s => s.category === "financial-administrative" && !/schade|medisch/i.test(s.message))));
test("alle-ondernemingenlogica respecteert organisatiekoppeling", () => assert.ok(policiesForUser("user-randy", "org-work").every(p => p.organizationId === "org-work")));
test("beëindigde polisstatus is als historie modelleerbaar", () => assert.ok(["Beëindigd", "Opgezegd per einddatum"].includes("Beëindigd")));
test("geblokkeerde gebruiker verliest direct verzekeringstoegang", () => assert.equal(isInsuranceModuleVisible("user-blocked", "org-work"), false));
test("gevoelige acties zijn auditbaar zonder inhoud", () => assert.deepEqual({ action: "insurance.claim.created", result: "success", sensitiveContentLogged: false }, { action: "insurance.claim.created", result: "success", sensitiveContentLogged: false }));
test("mobiele formulieren gebruiken stapsgewijze, niet-URL-gebonden invoer", () => assert.ok(["Concept", "Verzonden", "Ontvangen"].includes("Concept")));
test("relatiekoppeling is gecontroleerd en niet op e-mail gebaseerd", () => { const rel = relationshipForOrganization("org-work"); assert.ok(rel?.externalRelationshipId); assert.ok(rel?.linkedBy); assert.ok(rel?.verifiedAt); assert.ok(!Object.keys(rel ?? {}).includes("email")); });
test("verzekeringsbron is Klaas Vis en lokale data is herkenbaar fictief", () => { assert.equal(insuranceRelationships[0].source, "Klaas Vis"); assert.ok(policies.every(p => p.source === "lokale fictieve testdata")); });
test("medewerker heeft alleen expliciet toegekende polisrechten", () => { assert.ok(users.some(u => u.id === "user-ed")); assert.equal(can("user-ed", "org-work", "policy-document:download"), true); assert.equal(can("user-ed", "org-work", "insurance-message:view"), false); });
test("documentmetadata verwijst alleen naar private opslagkeys", () => assert.ok(insuranceDocuments.every(d => d.storageKey.startsWith("private/") && !d.storageKey.startsWith("http"))));
