import test from "node:test";
import assert from "node:assert/strict";
import { activeMemberships, authorizedOrganizations, can, isLastOwner, membershipFor, resolveOrganizationContext } from "../lib/access.ts";
import { invitations, invoices, organizations, requests, users } from "../lib/seed.ts";
test("demo bevat precies één onderneming", () => assert.deepEqual(organizations.map(o => o.id), ["org-work"]));
test("eigenaar krijgt uitsluitend de demo-onderneming", () => assert.deepEqual(authorizedOrganizations("user-randy").map(o => o.id), ["org-work"]));
test("alle context herstelt naar de enige onderneming", () => assert.equal(resolveOrganizationContext("user-randy", "all"), "org-work"));
test("factuur blijft gekoppeld aan actieve onderneming", () => assert.ok(invoices.every(i => organizations.some(o => o.id === i.organizationId))));
test("document blijft gekoppeld aan actieve onderneming", () => assert.ok(requests.every(d => organizations.some(o => o.id === d.organizationId))));
test("niet-bestaande onderneming wordt geweigerd", () => assert.equal(membershipFor("user-ed", "org-onbekend"), undefined));
test("gemanipuleerde organization_id heeft geen geldige membership", () => assert.equal(can("user-ed", "org-onbekend", "dashboard:view"), false));
test("alle administratiegegevens horen bij de ene demo-onderneming", () => assert.ok([...invoices, ...requests].every(item => item.organizationId === "org-work")));
test("ongeldige opgeslagen context herstelt veilig", () => assert.equal(resolveOrganizationContext("user-randy", "org-onbekend"), "org-work"));
test("klant met één onderneming krijgt geen extra keuzestap", () => assert.equal(authorizedOrganizations("user-randy").length, 1));
test("historische medewerkerfixture bevat geen inlogadres", () => { const user = users.find(u => u.id === "user-ed"); assert.equal(user?.accountStatus, "Actief"); assert.equal(user?.email, ""); });
test("uitnodiging heeft correcte status en vervaldatum", () => { assert.equal(invitations[0].status, "Uitgenodigd"); assert.ok(new Date(invitations[0].expiresAt) > new Date(invitations[0].invitedAt)); });
test("eigenaar kan gebruikers van de demo-onderneming beheren", () => assert.equal(can("user-randy", "org-work", "users:manage"), true));
test("financieel medewerker kan facturen en documenten verwerken maar geen gebruikers beheren", () => { assert.equal(can("user-ed", "org-work", "invoice:create"), true); assert.equal(can("user-ed", "org-work", "document:upload"), true); assert.equal(can("user-ed", "org-work", "users:view"), false); });
test("geblokkeerde gebruiker verliest direct alle memberships", () => assert.equal(activeMemberships("user-blocked").length, 0));
test("laatste eigenaar wordt herkend en kan niet worden verwijderd", () => assert.equal(isLastOwner("user-randy", "org-work"), true));
