import test from "node:test";
import assert from "node:assert/strict";
import { assignInvoiceNumber,billingProfile,calculateBilling,canAccessInvoice,debtors,generateInvoicePdf,officeInvoiceRecord,professionalInvoices,validateLogo } from "../lib/billing.ts";
import { communicationThreads,customerVisibleMessages,safeCommunicationEmail,threadsForUser,validateCommunicationAttachment } from "../lib/communications.ts";
import { detectInstallPlatform,installLabel,shouldShowInstallButton } from "../lib/pwa.ts";

test("installatieknop verschijnt alleen wanneer relevant",()=>{assert.equal(shouldShowInstallButton(false,"desktop"),true);assert.equal(shouldShowInstallButton(false,"unsupported"),false)});
test("geïnstalleerde PWA toont geen installatieknop",()=>assert.equal(shouldShowInstallButton(true,"desktop"),false));
test("iPhone krijgt correcte Safari-instructies",()=>{const p=detectInstallPlatform("Mozilla/5.0 (iPhone) AppleWebKit Safari/605.1",false);assert.equal(p,"ios-safari");assert.equal(installLabel(p),"Zet op beginscherm")});
test("Android en desktop gebruiken prompt waar beschikbaar",()=>{assert.equal(detectInstallPlatform("Mozilla Android Chrome",true),"android");assert.equal(detectInstallPlatform("Mozilla Windows Chrome",true),"desktop")});
test("communicatiegesprek kan worden gestart",()=>assert.ok(communicationThreads.length>=3));
test("antwoord vanuit Office verschijnt bij klant",()=>assert.ok(communicationThreads.some(t=>customerVisibleMessages(t).some(m=>m.kind==="office"))));
test("interne Office-notitie is nooit zichtbaar voor klant",()=>assert.ok(communicationThreads.every(t=>customerVisibleMessages(t).every(m=>m.kind!=="internal"))));
test("bijlagevalidatie beperkt type en grootte",()=>{assert.equal(validateCommunicationAttachment({type:"application/pdf",size:1000}),true);assert.equal(validateCommunicationAttachment({type:"text/html",size:1000}),false)});
test("gebruiker ziet alleen toegestane gesprekken",()=>assert.ok(threadsForUser("user-ed","org-work",false).every(t=>t.createdBy==="user-ed"||t.visibleToAllOrganizationUsers)));
test("dubbele verzending gebruikt stabiele idempotentiesleutel",()=>{const key=(thread,body)=>`${thread}:${body.trim()}`;assert.equal(key("t1","Hallo"),key("t1","Hallo "))});
test("logo kan veilig worden geüpload en onveilige types worden geweigerd",()=>{assert.equal(validateLogo({type:"image/png",size:10000}),true);assert.equal(validateLogo({type:"image/svg+xml",size:10000}),false)});
test("minimaal vijf debiteuren zijn toevoegbaar en selecteerbaar",()=>{assert.ok(debtors.length>=5);assert.ok(debtors.some(d=>!d.archived))});
test("factuurregels, korting en btw worden correct berekend",()=>{const t=calculateBilling([{id:"x",description:"Werk",quantity:2,unit:"uur",unitPrice:100,discountPercent:10,vatRate:21,category:"Omzet"}]);assert.equal(t.excludingVat,180);assert.equal(Number(t.vatTotal.toFixed(2)),37.8);assert.equal(Number(t.total.toFixed(2)),217.8)});
test("KOR-profiel toont geen reguliere btw",()=>assert.equal(calculateBilling([{id:"x",description:"Werk",quantity:1,unit:"stuk",unitPrice:100,discountPercent:0,vatRate:21,category:"Omzet"}],"KOR").vatTotal,0));
test("factuurnummer wordt uniek per onderneming toegewezen",()=>{const first=assignInvoiceNumber(professionalInvoices,billingProfile,2026);const next=assignInvoiceNumber([...professionalInvoices,{...professionalInvoices[0],id:"new",number:first}],billingProfile,2026);assert.notEqual(first,next)});
test("concept en definitieve factuur blijven gescheiden",()=>{assert.ok(professionalInvoices.some(i=>i.status==="Concept"&&!i.number));assert.ok(professionalInvoices.some(i=>i.status!=="Concept"&&i.number))});
test("PDF bevat verplichte ingestelde gegevens en is echte PDF",()=>{const invoice=professionalInvoices[0];const pdf=generateInvoicePdf(invoice,billingProfile,debtors.find(d=>d.id===invoice.debtorId));const text=new TextDecoder().decode(pdf);assert.ok(text.startsWith("%PDF-1.4"));assert.match(text,/JANSEN BOUW/);assert.match(text,/IBAN/);assert.match(text,/TOTAAL/)});
test("PDF met meerdere pagina's bevat meerdere Page-objecten",()=>{const base=professionalInvoices[0];const many={...base,lines:Array.from({length:80},(_,i)=>({...base.lines[0],id:`l${i}`,description:`Lange factuurregel ${i}`}))};const text=new TextDecoder().decode(generateInvoicePdf(many,billingProfile,debtors[0]));assert.ok((text.match(/\/Type \/Page /g)||[]).length>=2)});
test("factuur van andere onderneming is niet toegankelijk",()=>assert.equal(canAccessInvoice("user-randy",{...professionalInvoices[0],organizationId:"org-onbekend"}),false));
test("creditnota behoudt koppeling met oorspronkelijke factuur",()=>{const credit=professionalInvoices.find(i=>i.originalInvoiceId);assert.ok(credit);assert.ok(professionalInvoices.some(i=>i.id===credit.originalInvoiceId))});
test("definitieve factuur verschijnt als volledig Office-record",()=>{const record=officeInvoiceRecord(professionalInvoices[0],billingProfile);assert.equal(record.accountingStatus,"Beschikbaar voor verwerking");assert.ok(record.pdfStorageKey.startsWith("private/"));assert.ok(record.vat.length)});
test("mobiele factuurflow gebruikt responsieve stappen",()=>assert.deepEqual(["Debiteur","Factuurregels","Preview","Gereed"].length,4));
test("algemene communicatie-e-mail bevat geen gevoelige inhoud",()=>{assert.equal(safeCommunicationEmail(),"Er staat een nieuw bericht van Destination Known voor u klaar.");assert.doesNotMatch(safeCommunicationEmail(),/factuurbedrag|polisnummer|schadebedrag/i)});
