create extension if not exists pgcrypto;
create type public.account_status as enum ('invited','active','blocked','archived');
create type public.membership_status as enum ('active','revoked','expired');
create type public.message_visibility as enum ('customer','office_internal');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,email text not null unique,display_name text not null,account_status public.account_status not null default 'invited',mfa_required boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.customer_relationships(id uuid primary key default gen_random_uuid(),name text not null,status text not null default 'active',created_at timestamptz not null default now(),archived_at timestamptz);
create table public.organization_groups(id uuid primary key default gen_random_uuid(),customer_relationship_id uuid not null references public.customer_relationships(id),name text not null,created_at timestamptz not null default now());
create table public.organizations(id uuid primary key default gen_random_uuid(),customer_relationship_id uuid not null references public.customer_relationships(id),group_id uuid references public.organization_groups(id),name text not null,legal_name text,registration_number text,test_record boolean not null default true,created_at timestamptz not null default now(),archived_at timestamptz);
create table public.roles(id uuid primary key default gen_random_uuid(),scope text not null check(scope in('customer','office')),code text not null,display_name text not null,unique(scope,code));
create table public.permissions(id uuid primary key default gen_random_uuid(),code text not null unique,description text not null);
create table public.role_permissions(role_id uuid not null references public.roles(id) on delete cascade,permission_id uuid not null references public.permissions(id) on delete cascade,primary key(role_id,permission_id));
create table public.organization_memberships(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),user_id uuid not null references public.profiles(id),role_id uuid not null references public.roles(id),status public.membership_status not null default 'active',valid_from timestamptz not null default now(),valid_until timestamptz,unique(organization_id,user_id));
create table public.office_memberships(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references public.profiles(id),role_id uuid not null references public.roles(id),status public.membership_status not null default 'active',created_at timestamptz not null default now());
create table public.organization_features(organization_id uuid not null references public.organizations(id),feature_code text not null,enabled boolean not null default false,primary key(organization_id,feature_code));
create table public.customer_invitations(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),email text not null,role_id uuid not null references public.roles(id),token_hash text not null unique,expires_at timestamptz not null,accepted_at timestamptz,revoked_at timestamptz,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
create table public.debtors(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),name text not null,email text,address jsonb not null default '{}',payment_term_days integer not null default 30,created_at timestamptz not null default now(),archived_at timestamptz);
create table public.sales_invoices(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),debtor_id uuid not null references public.debtors(id),invoice_number text,status text not null default 'draft',invoice_date date not null,due_date date not null,currency char(3) not null default 'EUR',subtotal_cents bigint not null default 0,vat_cents bigint not null default 0,total_cents bigint not null default 0,paid_cents bigint not null default 0,pdf_storage_path text,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),finalized_at timestamptz,archived_at timestamptz,unique(organization_id,invoice_number));
create table public.sales_invoice_lines(id uuid primary key default gen_random_uuid(),invoice_id uuid not null references public.sales_invoices(id) on delete cascade,description text not null,quantity numeric(14,4) not null,unit_price_cents bigint not null,vat_rate numeric(5,2) not null,line_total_cents bigint not null,position integer not null,unique(invoice_id,position));
create table public.payments(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),invoice_id uuid references public.sales_invoices(id),amount_cents bigint not null check(amount_cents<>0),paid_at timestamptz not null,method text not null,reference text,status text not null default 'confirmed',created_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
create table public.documents(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),storage_path text not null unique,filename text not null,mime_type text not null,size_bytes bigint not null,status text not null default 'uploaded',uploaded_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),archived_at timestamptz);
create table public.document_requests(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),title text not null,status text not null default 'open',due_at timestamptz,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),completed_at timestamptz);
create table public.conversations(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),subject text not null,status text not null default 'open',created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),archived_at timestamptz);
create table public.conversation_participants(conversation_id uuid not null references public.conversations(id) on delete cascade,user_id uuid not null references public.profiles(id),last_read_at timestamptz,primary key(conversation_id,user_id));
create table public.messages(id uuid primary key default gen_random_uuid(),conversation_id uuid not null references public.conversations(id) on delete cascade,sender_id uuid not null references public.profiles(id),visibility public.message_visibility not null default 'customer',body text not null,idempotency_key uuid not null unique,created_at timestamptz not null default now());
create table public.appointments(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),title text not null,starts_at timestamptz not null,ends_at timestamptz not null,status text not null default 'planned',created_by uuid not null references public.profiles(id));
create table public.tasks(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),title text not null,status text not null default 'open',assigned_to uuid references public.profiles(id),due_at timestamptz,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
create table public.notifications(id uuid primary key default gen_random_uuid(),organization_id uuid references public.organizations(id),user_id uuid not null references public.profiles(id),type text not null,title text not null,read_at timestamptz,created_at timestamptz not null default now());
create table public.audit_events(id uuid primary key default gen_random_uuid(),actor_id uuid references public.profiles(id),customer_relationship_id uuid references public.customer_relationships(id),organization_id uuid references public.organizations(id),action text not null,object_type text not null,object_id uuid,result text not null,metadata jsonb not null default '{}',created_at timestamptz not null default now());

create index on public.organization_memberships(user_id,organization_id,status);create index on public.sales_invoices(organization_id,status,due_date);create index on public.messages(conversation_id,created_at);create index on public.documents(organization_id,status);create index on public.audit_events(organization_id,created_at desc);
create or replace function public.has_org_access(target uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.organization_memberships m join public.profiles p on p.id=m.user_id where m.user_id=auth.uid() and m.organization_id=target and m.status='active' and p.account_status='active' and (m.valid_until is null or m.valid_until>now()))$$;
create or replace function public.is_office_user() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.office_memberships m join public.profiles p on p.id=m.user_id where m.user_id=auth.uid() and m.status='active' and p.account_status='active')$$;
create or replace function public.has_aal2() returns boolean language sql stable as $$select coalesce((auth.jwt()->>'aal')='aal2',false)$$;

alter table public.profiles enable row level security;alter table public.organizations enable row level security;alter table public.organization_memberships enable row level security;alter table public.debtors enable row level security;alter table public.sales_invoices enable row level security;alter table public.sales_invoice_lines enable row level security;alter table public.payments enable row level security;alter table public.documents enable row level security;alter table public.document_requests enable row level security;alter table public.conversations enable row level security;alter table public.conversation_participants enable row level security;alter table public.messages enable row level security;alter table public.appointments enable row level security;alter table public.tasks enable row level security;alter table public.notifications enable row level security;alter table public.audit_events enable row level security;
create policy profiles_self_or_office on public.profiles for select using(id=auth.uid() or public.is_office_user());
create policy organizations_member_or_office on public.organizations for select using(public.has_org_access(id) or public.is_office_user());
create policy memberships_self_or_office on public.organization_memberships for select using(user_id=auth.uid() or public.is_office_user());
create policy debtors_read on public.debtors for select using(public.has_aal2() and (public.has_org_access(organization_id) or public.is_office_user()));create policy debtors_write on public.debtors for all using(public.has_aal2() and (public.has_org_access(organization_id) or public.is_office_user())) with check(public.has_aal2() and (public.has_org_access(organization_id) or public.is_office_user()));
create policy invoices_read on public.sales_invoices for select using(public.has_aal2() and (public.has_org_access(organization_id) or public.is_office_user()));create policy invoices_write on public.sales_invoices for all using(public.has_aal2() and (public.has_org_access(organization_id) or public.is_office_user())) with check(public.has_aal2() and (public.has_org_access(organization_id) or public.is_office_user()));
create policy invoice_lines_access on public.sales_invoice_lines for all using(exists(select 1 from public.sales_invoices i where i.id=invoice_id and (public.has_org_access(i.organization_id) or public.is_office_user()))) with check(exists(select 1 from public.sales_invoices i where i.id=invoice_id and (public.has_org_access(i.organization_id) or public.is_office_user())));
create policy payments_access on public.payments for all using(public.has_aal2() and (public.has_org_access(organization_id) or public.is_office_user())) with check(public.has_aal2() and (public.has_org_access(organization_id) or public.is_office_user()));
create policy documents_access on public.documents for all using(public.has_aal2() and (public.has_org_access(organization_id) or public.is_office_user())) with check(public.has_aal2() and (public.has_org_access(organization_id) or public.is_office_user()));
create policy requests_access on public.document_requests for all using(public.has_org_access(organization_id) or public.is_office_user()) with check(public.has_org_access(organization_id) or public.is_office_user());
create policy conversations_access on public.conversations for all using(public.has_org_access(organization_id) or public.is_office_user()) with check(public.has_org_access(organization_id) or public.is_office_user());
create policy messages_customer_read on public.messages for select using(exists(select 1 from public.conversations c where c.id=conversation_id and ((public.has_org_access(c.organization_id) and visibility='customer') or public.is_office_user())));create policy messages_insert on public.messages for insert with check(sender_id=auth.uid() and exists(select 1 from public.conversations c where c.id=conversation_id and (public.has_org_access(c.organization_id) or public.is_office_user())));
create policy tasks_access on public.tasks for all using(public.has_org_access(organization_id) or public.is_office_user()) with check(public.has_org_access(organization_id) or public.is_office_user());
create policy notifications_self on public.notifications for select using(user_id=auth.uid());
create policy audit_office_read on public.audit_events for select using(public.is_office_user());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('documents','documents',false,10485760,array['application/pdf','image/png','image/jpeg']),('invoice-pdfs','invoice-pdfs',false,10485760,array['application/pdf']),('company-assets','company-assets',false,2097152,array['image/png','image/jpeg']),('message-attachments','message-attachments',false,10485760,array['application/pdf','image/png','image/jpeg']) on conflict(id) do nothing;
create policy storage_read_authorized on storage.objects for select using(bucket_id in('documents','invoice-pdfs','company-assets','message-attachments') and public.has_aal2() and (public.has_org_access((storage.foldername(name))[1]::uuid) or public.is_office_user()));
create policy storage_insert_authorized on storage.objects for insert with check(bucket_id in('documents','invoice-pdfs','company-assets','message-attachments') and public.has_aal2() and public.has_org_access((storage.foldername(name))[1]::uuid));

insert into public.roles(scope,code,display_name) values('customer','owner','Eigenaar'),('customer','admin','Beheerder'),('customer','finance','Financieel medewerker'),('customer','documents','Documenten aanleveren'),('customer','viewer','Alleen bekijken'),('office','owner','Office-eigenaar'),('office','admin','Office-beheerder'),('office','accountant','Administrateur'),('office','handler','Behandelaar'),('office','viewer','Alleen bekijken') on conflict do nothing;
