-- Centrale contracten voor Destination Known Office en Mijn Destination Known.
CREATE TABLE customer_relationships (id TEXT PRIMARY KEY, name TEXT NOT NULL, main_contact_user_id TEXT, primary_assignee_id TEXT, secondary_assignee_id TEXT, created_at TEXT NOT NULL);
CREATE TABLE organization_groups (id TEXT PRIMARY KEY, customer_relationship_id TEXT NOT NULL REFERENCES customer_relationships(id), name TEXT NOT NULL);
CREATE TABLE organizations (id TEXT PRIMARY KEY, customer_relationship_id TEXT NOT NULL REFERENCES customer_relationships(id), group_id TEXT REFERENCES organization_groups(id), name TEXT NOT NULL, trade_name TEXT, legal_form TEXT NOT NULL, kvk TEXT NOT NULL UNIQUE, vat_number TEXT, rsin TEXT, iban TEXT, address TEXT, founded_at TEXT, fiscal_year INTEGER, status TEXT NOT NULL, organization_type TEXT NOT NULL, manager_id TEXT NOT NULL);
CREATE TABLE organization_relationships (id TEXT PRIMARY KEY, parent_organization_id TEXT NOT NULL REFERENCES organizations(id), child_organization_id TEXT NOT NULL REFERENCES organizations(id), relationship_type TEXT NOT NULL, ownership_percentage NUMERIC, starts_at TEXT NOT NULL, ends_at TEXT, note TEXT);
CREATE TABLE organization_profiles (organization_id TEXT PRIMARY KEY REFERENCES organizations(id), profile_json TEXT NOT NULL, valid_from TEXT NOT NULL, valid_to TEXT, source TEXT NOT NULL, changed_by TEXT NOT NULL, changed_at TEXT NOT NULL);
CREATE TABLE organization_features (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL REFERENCES organizations(id), module TEXT NOT NULL, status TEXT NOT NULL, starts_at TEXT, ends_at TEXT, source TEXT NOT NULL, reason TEXT, automatic INTEGER NOT NULL DEFAULT 1, changed_by TEXT NOT NULL, changed_at TEXT NOT NULL, pending_change_request_id TEXT, UNIQUE(organization_id,module));
CREATE TABLE portal_users (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, function_title TEXT, status TEXT NOT NULL, last_login_at TEXT, invited_at TEXT, invited_by TEXT);
CREATE TABLE memberships (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES portal_users(id), organization_id TEXT NOT NULL REFERENCES organizations(id), role TEXT NOT NULL, permissions_json TEXT NOT NULL, starts_at TEXT NOT NULL, ends_at TEXT);
CREATE TABLE organization_change_requests (id TEXT PRIMARY KEY, customer_relationship_id TEXT NOT NULL REFERENCES customer_relationships(id), organization_id TEXT NOT NULL REFERENCES organizations(id), requester_user_id TEXT NOT NULL REFERENCES portal_users(id), request_type TEXT NOT NULL, data_json TEXT NOT NULL, desired_effective_at TEXT, received_at TEXT NOT NULL, owner_id TEXT, status TEXT NOT NULL, internal_notes TEXT, missing_information_json TEXT, impacted_modules_json TEXT, impacted_tasks_json TEXT, processed_at TEXT);
CREATE INDEX idx_organizations_relationship ON organizations(customer_relationship_id);
CREATE INDEX idx_memberships_user_organization ON memberships(user_id,organization_id);
CREATE INDEX idx_change_requests_status ON organization_change_requests(status,owner_id);
