import type { Id } from "./models";
import { can } from "./access";

export type DebtorType = "Zakelijk" | "Particulier";
export interface BillingProfile { organizationId: Id; companyName: string; tradeName: string; address: string; postalCode: string; city: string; country: string; chamberOfCommerce: string; vatId: string; iban: string; bic?: string; email: string; phone: string; website: string; paymentTermDays: number; defaultVatRate: number; defaultHourlyRate: number; invoicePrefix: string; nextNumber: number; defaultText: string; paymentInstruction: string; footer: string; fiscalScheme: "Regulier" | "KOR"; logoPath?: string }
export interface Debtor { id: Id; organizationId: Id; type: DebtorType; companyName?: string; firstName?: string; lastName?: string; contactPerson?: string; address: string; postalCode: string; city: string; country: string; email: string; phone?: string; chamberOfCommerce?: string; vatId?: string; customerNumber: string; paymentTermDays: number; vatTreatment: "Nederlands" | "Verlegd" | "Vrijgesteld"; reference?: string; notes?: string; archived: boolean }
export interface BillingLine { id: Id; description: string; quantity: number; unit: "uur" | "stuk" | "dag" | "kilometer" | "maand" | "project" | "abonnement" | "anders"; unitPrice: number; discountPercent: number; vatRate: number; category: string }
export type InvoiceStatus = "Concept" | "Definitief" | "Klaar voor verzending" | "Verstuurd" | "Deels betaald" | "Betaald" | "Vervallen" | "Herinnering verstuurd" | "Gecrediteerd" | "Geannuleerd";
export interface ProfessionalInvoice { id: Id; organizationId: Id; debtorId: Id; number?: string; date: string; dueDate: string; reference?: string; lines: BillingLine[]; status: InvoiceStatus; sentAt?: string; lastReminderAt?: string; paidAmount: number; finalizedAt?: string; originalInvoiceId?: Id; creditReason?: string; accountingStatus: "Niet verwerkt" | "Beschikbaar voor verwerking" | "Verwerkt" }

export const billingProfile: BillingProfile = { organizationId: "org-work", companyName: "Jansen Bouw B.V.", tradeName: "Jansen Bouw", address: "Kade 18", postalCode: "3511 AB", city: "Utrecht", country: "Nederland", chamberOfCommerce: "88776655", vatId: "NL000000001B01", iban: "NL00 TEST 0123 4567 89", bic: "TESTNL2A", email: "administratie@jansenbouw.example", phone: "030-123 45 67", website: "www.jansenbouw.example", paymentTermDays: 30, defaultVatRate: 21, defaultHourlyRate: 85, invoicePrefix: "2026-", nextNumber: 37, defaultText: "Hartelijk dank voor uw opdracht.", paymentInstruction: "Gelieve het totaalbedrag onder vermelding van het factuurnummer over te maken.", footer: "Jansen Bouw B.V. · betrouwbaar gebouwd", fiscalScheme: "Regulier", logoPath: "/customer-logo.svg" };
export const debtors: Debtor[] = [
  { id: "deb-1", organizationId: "org-work", type: "Zakelijk", companyName: "Noord & Co B.V.", contactPerson: "M. de Boer", address: "Havenstraat 12", postalCode: "1013 AB", city: "Amsterdam", country: "Nederland", email: "facturen@noordenco.example", phone: "020-555 01 01", chamberOfCommerce: "12340001", vatId: "NL001234001B01", customerNumber: "KL-1001", paymentTermDays: 30, vatTreatment: "Nederlands", archived: false },
  { id: "deb-2", organizationId: "org-work", type: "Zakelijk", companyName: "Van Leeuwen Vastgoed", contactPerson: "S. van Leeuwen", address: "Stationsweg 4", postalCode: "3811 MJ", city: "Amersfoort", country: "Nederland", email: "boekhouding@vanleeuwen.example", chamberOfCommerce: "12340002", customerNumber: "KL-1002", paymentTermDays: 14, vatTreatment: "Nederlands", archived: false },
  { id: "deb-3", organizationId: "org-work", type: "Particulier", firstName: "Sophie", lastName: "Bakker", address: "Lindelaan 22", postalCode: "3701 CD", city: "Zeist", country: "Nederland", email: "sophie.bakker@example.test", customerNumber: "KL-1003", paymentTermDays: 14, vatTreatment: "Nederlands", archived: false },
  { id: "deb-4", organizationId: "org-work", type: "Zakelijk", companyName: "De Groene School", contactPerson: "P. Visser", address: "Schoolplein 8", postalCode: "3521 VA", city: "Utrecht", country: "Nederland", email: "financien@groeneschool.example", chamberOfCommerce: "12340004", customerNumber: "KL-1004", paymentTermDays: 30, vatTreatment: "Nederlands", archived: false },
  { id: "deb-5", organizationId: "org-work", type: "Zakelijk", companyName: "Studio Rivier", contactPerson: "A. Smit", address: "Werfkade 31", postalCode: "3511 ZX", city: "Utrecht", country: "Nederland", email: "admin@studiorivier.example", customerNumber: "KL-1005", paymentTermDays: 30, vatTreatment: "Nederlands", archived: true },
];
const line = (id: string, description: string, quantity: number, unitPrice: number, vatRate = 21): BillingLine => ({ id, description, quantity, unit: "uur", unitPrice, discountPercent: 0, vatRate, category: "Omzet diensten" });
export const professionalInvoices: ProfessionalInvoice[] = [
  { id: "pinv-1", organizationId: "org-work", debtorId: "deb-1", number: "2026-0031", date: "2026-09-02", dueDate: "2026-10-02", lines: [line("bl-1", "Bouwbegeleiding augustus", 18, 85)], status: "Verstuurd", sentAt: "2026-09-02T14:05:00+02:00", paidAmount: 0, finalizedAt: "2026-09-02T13:55:00+02:00", accountingStatus: "Beschikbaar voor verwerking" },
  { id: "pinv-2", organizationId: "org-work", debtorId: "deb-2", number: "2026-0032", date: "2026-08-12", dueDate: "2026-08-26", lines: [line("bl-2", "Renovatieadvies", 10, 95)], status: "Betaald", sentAt: "2026-08-12T10:00:00+02:00", paidAmount: 1149.5, finalizedAt: "2026-08-12T09:45:00+02:00", accountingStatus: "Verwerkt" },
  { id: "pinv-3", organizationId: "org-work", debtorId: "deb-3", number: "2026-0033", date: "2026-08-01", dueDate: "2026-08-15", lines: [line("bl-3", "Inspectie en rapportage", 5, 85)], status: "Vervallen", sentAt: "2026-08-01T12:00:00+02:00", lastReminderAt: "2026-09-01T09:00:00+02:00", paidAmount: 0, finalizedAt: "2026-08-01T11:45:00+02:00", accountingStatus: "Beschikbaar voor verwerking" },
  { id: "pinv-4", organizationId: "org-work", debtorId: "deb-4", date: "2026-09-18", dueDate: "2026-10-18", lines: [line("bl-4", "Projectvoorbereiding", 6, 85)], status: "Concept", paidAmount: 0, accountingStatus: "Niet verwerkt" },
  { id: "pinv-5", organizationId: "org-work", debtorId: "deb-1", date: "2026-09-19", dueDate: "2026-10-19", lines: [line("bl-5", "Meerwerk bouwbegeleiding", 4, 85)], status: "Concept", paidAmount: 0, accountingStatus: "Niet verwerkt" },
  { id: "credit-1", organizationId: "org-work", debtorId: "deb-1", number: "2026-0036", date: "2026-09-10", dueDate: "2026-09-10", lines: [line("bl-c1", "Credit correctie uren", -2, 85)], status: "Gecrediteerd", paidAmount: 0, finalizedAt: "2026-09-10T12:00:00+02:00", originalInvoiceId: "pinv-1", creditReason: "Correctie dubbel geregistreerde uren", accountingStatus: "Beschikbaar voor verwerking" },
];

export function calculateBilling(lines: BillingLine[], fiscalScheme: BillingProfile["fiscalScheme"] = "Regulier") { const perRate = new Map<number, number>(); let subtotal = 0; let discount = 0; for (const item of lines) { const gross = item.quantity * item.unitPrice; const reduction = gross * item.discountPercent / 100; const net = gross - reduction; const rate = fiscalScheme === "KOR" ? 0 : item.vatRate; subtotal += gross; discount += reduction; perRate.set(rate, (perRate.get(rate) ?? 0) + net * rate / 100); } const excludingVat = subtotal - discount; const vatTotal = [...perRate.values()].reduce((a,b) => a+b, 0); return { subtotal, discount, excludingVat, vatByRate: [...perRate.entries()].map(([rate, amount]) => ({ rate, amount })), vatTotal, total: excludingVat + vatTotal }; }
export function assignInvoiceNumber(existing: ProfessionalInvoice[], profile: BillingProfile, year: number) { const numbers = existing.filter(i => i.organizationId === profile.organizationId && i.number).map(i => Number(i.number!.replace(/\D/g, "").slice(-4))).filter(Number.isFinite); const sequence = Math.max(profile.nextNumber - 1, ...numbers, 0) + 1; return `${profile.invoicePrefix.replace("2026", String(year))}${String(sequence).padStart(4,"0")}`; }
export function debtorName(debtor: Debtor) { return debtor.companyName || `${debtor.firstName ?? ""} ${debtor.lastName ?? ""}`.trim(); }
export function validateLogo(file: { type: string; size: number }) { return ["image/png", "image/jpeg"].includes(file.type) && file.size > 0 && file.size <= 2_000_000; }
export function canAccessInvoice(userId:string,invoice:ProfessionalInvoice){return can(userId,invoice.organizationId,"invoices:view")}
export function officeInvoiceRecord(invoice:ProfessionalInvoice,profile:BillingProfile){const totals=calculateBilling(invoice.lines,profile.fiscalScheme);return {organizationId:invoice.organizationId,invoiceId:invoice.id,number:invoice.number,date:invoice.date,dueDate:invoice.dueDate,total:totals.total,vat:totals.vatByRate,status:invoice.status,pdfStorageKey:`private/${invoice.organizationId}/invoices/${invoice.id}.pdf`,accountingStatus:invoice.accountingStatus}}

function pdfEscape(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^\x20-\x7E]/g, "?").replace(/[()\\]/g, c => `\\${c}`); }
export function generateInvoicePdf(invoice: ProfessionalInvoice, profile: BillingProfile, debtor: Debtor) { const totals = calculateBilling(invoice.lines, profile.fiscalScheme); const rows = invoice.lines.map((l,i) => `${i+1}. ${l.description}  ${l.quantity} ${l.unit} x EUR ${l.unitPrice.toFixed(2)}  EUR ${(l.quantity*l.unitPrice*(1-l.discountPercent/100)).toFixed(2)}`); const base = [profile.tradeName.toUpperCase(), profile.companyName, `${profile.address}, ${profile.postalCode} ${profile.city}`, `KvK ${profile.chamberOfCommerce}  BTW ${profile.vatId}`, "", invoice.status === "Concept" ? "CONCEPTFACTUUR" : `FACTUUR ${invoice.number}`, `Factuurdatum ${invoice.date}  Vervaldatum ${invoice.dueDate}`, "", `Aan: ${debtorName(debtor)}`, `${debtor.address}, ${debtor.postalCode} ${debtor.city}`, `Klantnummer ${debtor.customerNumber}${invoice.reference ? `  Referentie ${invoice.reference}` : ""}`, "", ...rows, "", `Subtotaal EUR ${totals.excludingVat.toFixed(2)}`, ...totals.vatByRate.map(v => `BTW ${v.rate}% EUR ${v.amount.toFixed(2)}`), `TOTAAL EUR ${totals.total.toFixed(2)}`, "", profile.paymentInstruction, `IBAN ${profile.iban}`, "", profile.footer]; const chunks: string[][]=[]; for(let i=0;i<base.length;i+=34) chunks.push(base.slice(i,i+34)); const objects:string[]=[]; const add=(s:string)=>{objects.push(s);return objects.length}; const font=add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"); const pagesRef=objects.length+1; objects.push(""); const pageRefs:number[]=[]; for (let p=0;p<chunks.length;p++) { const lines=chunks[p]; const commands=["BT","/F1 10 Tf","48 790 Td",...lines.flatMap((text,index)=>index===0?[`(${pdfEscape(text)}) Tj`]:["0 -20 Td",`(${pdfEscape(text)}) Tj`]),"0 -24 Td",`(Pagina ${p+1} van ${chunks.length}) Tj`,"ET"].join("\n"); const stream=add(`<< /Length ${commands.length} >>\nstream\n${commands}\nendstream`); const page=add(`<< /Type /Page /Parent ${pagesRef} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font} 0 R >> >> /Contents ${stream} 0 R >>`); pageRefs.push(page); } objects[pagesRef-1]=`<< /Type /Pages /Kids [${pageRefs.map(r=>`${r} 0 R`).join(" ")}] /Count ${pageRefs.length} >>`; const catalog=add(`<< /Type /Catalog /Pages ${pagesRef} 0 R >>`); let pdf="%PDF-1.4\n"; const offsets=[0]; objects.forEach((obj,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${obj}\nendobj\n`}); const xref=pdf.length; pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(o=>`${String(o).padStart(10,"0")} 00000 n `).join("\n")}\ntrailer\n<< /Size ${objects.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`; return new TextEncoder().encode(pdf); }
