import type { Id } from "./models";
export type ConversationStatus = "Concept" | "Verzonden" | "Ontvangen" | "In behandeling" | "Aanvullende informatie nodig" | "Wacht op klant" | "Doorgezet" | "Afgerond" | "Gesloten" | "Gearchiveerd";
export type MessageKind = "customer" | "office" | "system" | "internal";
export interface CommunicationMessage { id: Id; kind: MessageKind; senderId: Id; senderName: string; senderRole: string; body: string; createdAt: string; attachments: Array<{ id: Id; name: string; storageKey: string }>; readByCustomer: boolean }
export interface ServiceRequest { summary: string; requestedAt: string; status: ConversationStatus; assignee: string; missingInformation?: string; nextStep: string; completedAt?: string }
export interface CommunicationThread { id: Id; organizationId: Id; createdBy: Id; visibleToAllOrganizationUsers: boolean; subject: string; category: string; status: ConversationStatus; priority: "Normaal" | "Hoog"; assignee: string; deadline?: string; archived: boolean; messages: CommunicationMessage[]; request?: ServiceRequest }
export const communicationCategories = ["Vraag over administratie","Factuur of boeking","Document aanleveren","Belasting of aangifte","Afspraak","Bedrijfswijziging","Personeel","Voertuig","Verzekering via Klaas Vis","Technisch probleem","Anders"];
export const communicationThreads: CommunicationThread[] = [
 { id:"thread-1", organizationId:"org-work", createdBy:"user-randy", visibleToAllOrganizationUsers:true, subject:"Materieel zakelijk boeken", category:"Factuur of boeking", status:"In behandeling", priority:"Normaal", assignee:"Randy", deadline:"2026-09-25", archived:false, messages:[{id:"cm-1",kind:"customer",senderId:"user-randy",senderName:"Jan Jansen",senderRole:"Eigenaar",body:"Kan ik de aanschaf van het nieuwe materieel zakelijk laten verwerken?",createdAt:"2026-09-15T10:24:00+02:00",attachments:[],readByCustomer:true},{id:"cm-2",kind:"office",senderId:"office-randy",senderName:"Randy",senderRole:"Administratieadviseur",body:"Ja. Wilt u de aankoopfactuur en het betaalbewijs toevoegen?",createdAt:"2026-09-15T14:18:00+02:00",attachments:[],readByCustomer:false},{id:"int-1",kind:"internal",senderId:"office-ed",senderName:"Ed",senderRole:"Boekhouding",body:"Intern: controleer investeringsdrempel.",createdAt:"2026-09-15T14:22:00+02:00",attachments:[],readByCustomer:false}], request:{summary:"Aankoop materieel beoordelen",requestedAt:"2026-09-15",status:"Wacht op klant",assignee:"Randy",missingInformation:"Aankoopfactuur en betaalbewijs",nextStep:"Klant levert documenten aan"}},
 { id:"thread-2", organizationId:"org-work", createdBy:"user-randy", visibleToAllOrganizationUsers:true, subject:"Btw-aangifte derde kwartaal", category:"Belasting of aangifte", status:"Afgerond", priority:"Normaal", assignee:"Ed", archived:false, messages:[{id:"cm-3",kind:"office",senderId:"office-ed",senderName:"Ed",senderRole:"Boekhouder",body:"De aangifte is gecontroleerd en staat klaar.",createdAt:"2026-09-16T09:10:00+02:00",attachments:[],readByCustomer:true},{id:"sys-1",kind:"system",senderId:"system",senderName:"Systeem",senderRole:"Statusmelding",body:"Verzoek afgerond.",createdAt:"2026-09-16T09:12:00+02:00",attachments:[],readByCustomer:true}], request:{summary:"Btw-aangifte controleren",requestedAt:"2026-09-10",status:"Afgerond",assignee:"Ed",nextStep:"Geen actie nodig",completedAt:"2026-09-16"}},
 { id:"thread-3", organizationId:"org-work", createdBy:"user-ed", visibleToAllOrganizationUsers:false, subject:"Ontbrekende tankbon", category:"Document aanleveren", status:"Aanvullende informatie nodig", priority:"Hoog", assignee:"Ed", archived:false, messages:[{id:"cm-4",kind:"office",senderId:"office-ed",senderName:"Ed",senderRole:"Boekhouder",body:"Wilt u de tankbon van 16 september toevoegen?",createdAt:"2026-09-18T11:05:00+02:00",attachments:[],readByCustomer:false}]},
];
export function customerVisibleMessages(thread: CommunicationThread) { return thread.messages.filter(message => message.kind !== "internal"); }
export function threadsForUser(userId: string, organizationId: string, canViewOthers: boolean) { return communicationThreads.filter(t => t.organizationId === organizationId && (canViewOthers || t.createdBy === userId || t.visibleToAllOrganizationUsers)); }
export function safeCommunicationEmail() { return "Er staat een nieuw bericht van Destination Known voor u klaar."; }
export function validateCommunicationAttachment(file: { type: string; size: number }) { return ["application/pdf","image/jpeg","image/png"].includes(file.type) && file.size > 0 && file.size <= 10_000_000; }
