import type { Id, Permission } from "./models";
import { can } from "./access";

export type InsurancePermission = Extract<Permission, `insurance${string}` | `policy${string}` | `claim${string}`>;
export type InsuranceRelationshipStatus = "not-applicable" | "private-only" | "business-only" | "private-and-business" | "application-only" | "active" | "checking" | "ended";
export interface InsuranceRelationship { id: Id; customerId: Id; organizationId?: Id; status: InsuranceRelationshipStatus; source: "Klaas Vis"; externalRelationshipId: string; validFrom: string; validUntil?: string; linkedAt: string; linkedBy: string; verifiedAt: string }
export interface InsuranceParty { id: Id; type: "person" | "organization" | "household" | "employer"; userId?: Id; organizationId?: Id; displayName: string }
export interface PolicyHolder { partyId: Id; name: string }
export interface InsuredParty { partyId: Id; name: string }
export interface InsuredObject { id: Id; type: "vehicle" | "building" | "inventory" | "liability" | "other"; description: string; registration?: string; address?: string }
export interface Coverage { name: string; description: string; confirmed: boolean }
export interface Insurer { id: Id; name: string; emergencyPhone?: string }
export type PolicyStatus = "Aangevraagd" | "In behandeling" | "Actief" | "Wijziging in behandeling" | "Opgezegd per einddatum" | "Beëindigd" | "Geschorst" | "Onbekend of controle nodig";
export interface Policy { id: Id; externalSourceId: string; policyNumber: string; insurerId: Id; holder: PolicyHolder; insuredParties: InsuredParty[]; organizationId?: Id; personalUserId?: Id; productType: string; productName: string; status: PolicyStatus; startDate: string; endDate?: string; contractRenewalDate?: string; paymentTerm: string; premium?: number; insuredObject: InsuredObject; coverage: Coverage[]; adviser: string; lastSynchronizedAt: string; source: "ANVA" | "lokale fictieve testdata" }
export interface InsuranceDocument { id: Id; policyId: Id; organizationId?: Id; personalUserId?: Id; name: string; type: string; date: string; version: string; storageKey: string; source: string }
export type InsuranceRequestStatus = "Concept" | "Verzonden" | "Ontvangen" | "Aanvullende informatie nodig" | "In behandeling bij Klaas Vis" | "Doorgezet naar verzekeraar" | "Bevestigd" | "Afgewezen" | "Ingetrokken";
export interface ClaimTimelineEvent { id: Id; at: string; status: string; publicMessage: string; actor: "Klant" | "Klaas Vis" | "Verzekeraar" }
export interface InsuranceChangeRequest { id: Id; policyId: Id; organizationId?: Id; requestedBy: Id; kind: string; effectiveDate: string; explanation: string; status: InsuranceRequestStatus; timeline: ClaimTimelineEvent[] }
export interface ClaimParty { id: Id; role: string; displayName: string }
export interface ClaimDocument { id: Id; claimId: Id; name: string; type: string; storageKey: string; status: "Ontvangen" | "Gevraagd" }
export interface Claim { id: Id; reference: string; externalClaimNumber?: string; policyId: Id; organizationId?: Id; personalUserId?: Id; incidentAt: string; incidentType: string; status: "Concept" | "Gemeld" | "In beoordeling" | "Aanvullende informatie nodig" | "Doorgezet naar verzekeraar" | "Expert ingeschakeld" | "Dekking wordt beoordeeld" | "Akkoord" | "Afgewezen" | "Uitkering volgt" | "Afgerond" | "Gesloten"; handler: string; parties: ClaimParty[]; timeline: ClaimTimelineEvent[]; nextAction?: string }
export interface InsuranceConversation { id: Id; organizationId?: Id; personalUserId?: Id; policyId?: Id; claimId?: Id; subject: string; messages: Array<{ id: Id; sender: string; text: string; at: string }> }
export interface InsuranceIntegrationLink { id: Id; relationshipId: Id; system: "ANVA" | "DDI" | "Microsoft Graph" | "Klaas Vis AI Workforce"; externalId: string; lastSynchronizedAt: string }
export interface InsuranceReferral { id: Id; customerId: Id; organizationId?: Id; origin: "rechtstreeks via Klaas Vis" | "via Destination Known Administraties" | "bestaande gezamenlijke klant" | "andere herkomst"; status: string; createdAt: string }

export const klaasVisContact = { fullName: "BV Assurantiekantoor Klaas Vis Ao. 1834", phone: "075-631 42 61", email: "info@klaasvis.nl", website: "https://www.klaasvis.nl", address: "Zuiderweg 7, 1456 NC Wijdewormer", openingHours: "Werkdagen 09:00–16:00", emergencyInstructions: "Is er sprake van direct gevaar, ernstig letsel, brand, diefstal of een noodsituatie? Neem dan direct contact op met de hulpdiensten of het toepasselijke alarmnummer." } as const;
export const insuranceRelationships: InsuranceRelationship[] = [{ id: "ins-rel-1", customerId: "customer-jansen", organizationId: "org-work", status: "business-only", source: "Klaas Vis", externalRelationshipId: "KV-REL-DEMO-4102", validFrom: "2025-01-01", linkedAt: "2026-08-14T10:15:00+02:00", linkedBy: "Klaas Vis relatiebeheer", verifiedAt: "2026-09-16T09:00:00+02:00" }];
export const insuranceParties: InsuranceParty[] = [{ id: "party-jansen-bouw", type: "organization", organizationId: "org-work", displayName: "Jansen Bouw B.V." }];
export const insurers: Insurer[] = [{ id: "insurer-asr", name: "a.s.r." }, { id: "insurer-nn", name: "Nationale-Nederlanden" }];
export const policies: Policy[] = [
  { id: "policy-liability", externalSourceId: "ANVA-DEMO-84001", policyNumber: "KV-DEMO-AVB-2026", insurerId: "insurer-asr", holder: { partyId: "party-jansen-bouw", name: "Jansen Bouw B.V." }, insuredParties: [{ partyId: "party-jansen-bouw", name: "Jansen Bouw B.V." }], organizationId: "org-work", productType: "Bedrijfsaansprakelijkheid", productName: "Bedrijf Compact AVB", status: "Actief", startDate: "2025-01-01", contractRenewalDate: "2027-01-01", paymentTerm: "Per kwartaal", premium: 186.40, insuredObject: { id: "object-business", type: "liability", description: "Bouw- en onderhoudswerkzaamheden" }, coverage: [{ name: "Bedrijfsaansprakelijkheid", description: "Dekking volgens het laatst bevestigde polisblad.", confirmed: true }], adviser: "Team Zakelijk Klaas Vis", lastSynchronizedAt: "2026-09-18T08:45:00+02:00", source: "lokale fictieve testdata" },
  { id: "policy-vehicle", externalSourceId: "ANVA-DEMO-84002", policyNumber: "KV-DEMO-AUTO-2026", insurerId: "insurer-nn", holder: { partyId: "party-jansen-bouw", name: "Jansen Bouw B.V." }, insuredParties: [{ partyId: "party-jansen-bouw", name: "Jansen Bouw B.V." }], organizationId: "org-work", productType: "Bedrijfsauto", productName: "Zakelijke autoverzekering", status: "Wijziging in behandeling", startDate: "2026-02-01", contractRenewalDate: "2027-02-01", paymentTerm: "Per maand", premium: 128.75, insuredObject: { id: "object-vehicle", type: "vehicle", description: "Volvo XC40", registration: "1-ABC-23" }, coverage: [{ name: "Casco", description: "De actuele dekking wordt door Klaas Vis bevestigd.", confirmed: false }], adviser: "Team Mobiliteit Klaas Vis", lastSynchronizedAt: "2026-09-18T08:47:00+02:00", source: "lokale fictieve testdata" },
];
export const insuranceDocuments: InsuranceDocument[] = [{ id: "ins-doc-1", policyId: "policy-liability", organizationId: "org-work", name: "Polisblad bedrijfsaansprakelijkheid", type: "Polisblad", date: "2026-01-02", version: "2026.1", storageKey: "private/org-work/policy-liability/polisblad-2026.pdf", source: "DDI" }, { id: "ins-doc-2", policyId: "policy-vehicle", organizationId: "org-work", name: "Wijzigingsbevestiging bedrijfsauto", type: "Wijzigingsbevestiging", date: "2026-09-15", version: "1", storageKey: "private/org-work/policy-vehicle/wijziging-1.pdf", source: "DDI" }];
export const changeRequests: InsuranceChangeRequest[] = [{ id: "change-1", policyId: "policy-vehicle", organizationId: "org-work", requestedBy: "user-randy", kind: "Voertuig vervangen", effectiveDate: "2026-10-01", explanation: "Nieuwe bedrijfsauto aangemeld; kentekenbewijs ontbreekt nog.", status: "Aanvullende informatie nodig", timeline: [{ id: "evt-c1", at: "2026-09-17T10:20:00+02:00", status: "Ontvangen", publicMessage: "Uw verzoek is ontvangen door Klaas Vis.", actor: "Klaas Vis" }, { id: "evt-c2", at: "2026-09-18T09:05:00+02:00", status: "Aanvullende informatie nodig", publicMessage: "Upload het kentekenbewijs van de nieuwe bedrijfsauto.", actor: "Klaas Vis" }] }];
export const claims: Claim[] = [];
export const insuranceConversations: InsuranceConversation[] = [{ id: "ins-conv-1", organizationId: "org-work", policyId: "policy-vehicle", subject: "Kentekenbewijs nieuwe bedrijfsauto", messages: [{ id: "im-1", sender: "Klaas Vis", text: "Wilt u het kentekenbewijs veilig toevoegen aan het wijzigingsverzoek?", at: "2026-09-18T09:05:00+02:00" }] }];
export const integrationLinks: InsuranceIntegrationLink[] = [{ id: "link-anva-1", relationshipId: "ins-rel-1", system: "ANVA", externalId: "ANVA-DEMO-4102", lastSynchronizedAt: "2026-09-18T08:47:00+02:00" }];
export const referrals: InsuranceReferral[] = [];
export const insuranceScenarioFixtures = [
  { id: "A", organizations: 1, privatePolicies: 0, businessPolicies: 2, relationship: "active", claimStatus: null, note: "Eigenaar volledig; medewerker alleen polisdocumenten." },
  { id: "B", organizations: 2, privatePolicies: 0, businessPolicies: 2, relationship: "work-company-only", claimStatus: null, note: "Holding zonder lege module; groepsoverzicht toont alleen relevante polissen." },
  { id: "C", organizations: 1, privatePolicies: 2, businessPolicies: 2, relationship: "private-and-business", claimStatus: null, note: "Privé uitsluitend eigenaar; medewerker alleen toegestane zakelijke stukken." },
  { id: "D", organizations: 1, privatePolicies: 0, businessPolicies: 0, relationship: "application-only", claimStatus: null, note: "Lopende adviesaanvraag via Destination Known, geen actieve polis." },
  { id: "E", organizations: 1, privatePolicies: 0, businessPolicies: 1, relationship: "active", claimStatus: "Aanvullende informatie nodig", note: "Eigenaar kan reageren en uploaden; andere medewerker ziet dossier niet." },
] as const;
export const generalInsuranceEmail = "Er staat een nieuw bericht over uw verzekering voor u klaar.";
export function validateInsuranceUpload(file: { size: number; type: string }) { return file.size > 0 && file.size <= 10_000_000 && ["application/pdf", "image/jpeg", "image/png", "video/mp4"].includes(file.type); }

export function relationshipForOrganization(organizationId: string) { return insuranceRelationships.find(r => r.organizationId === organizationId && ["business-only", "private-and-business", "active", "application-only", "checking", "ended"].includes(r.status)); }
export function isInsuranceModuleVisible(userId: string, organizationId: string) { return Boolean(relationshipForOrganization(organizationId)) && can(userId, organizationId, "insurance:view"); }
export function policiesForUser(userId: string, organizationId: string) { if (!can(userId, organizationId, "policy:view")) return []; return policies.filter(p => p.organizationId === organizationId || p.personalUserId === userId); }
export function canAccessInsuranceDocument(userId: string, documentId: string) { const document = insuranceDocuments.find(d => d.id === documentId); if (!document) return false; if (document.personalUserId) return document.personalUserId === userId; return Boolean(document.organizationId && can(userId, document.organizationId, "policy-document:download")); }
export function officeInsuranceSignals(organizationId: string) { return policies.filter(p => p.organizationId === organizationId).map(p => ({ organizationId, policyId: p.id, category: "financial-administrative" as const, message: `Zakelijke verzekeringspremie ${p.policyNumber} beschikbaar voor verwerking` })); }
