import { calculateBilling, type BillingProfile, type ProfessionalInvoice } from "./billing";

export interface Payment { id:string; invoiceId:string; amount:number; paidAt:string; method:string; reference?:string; correction?:boolean }
export interface ReminderState { level:0|1|2|3; lastSentAt?:string; paused?:boolean; disputed?:boolean; arrangement?:boolean; pendingPayment?:boolean }
export interface ReceivableSettings { dueSoonDays:number; firstReminderDays:number; minimumReminderIntervalDays:number; followUpDays:number }
export const receivableSettings:ReceivableSettings={dueSoonDays:7,firstReminderDays:1,minimumReminderIntervalDays:7,followUpDays:7};

function day(value:string){return new Date(`${value.slice(0,10)}T12:00:00+02:00`)}
export function daysFromDue(dueDate:string,today="2026-09-22"){return Math.round((day(dueDate).getTime()-day(today).getTime())/86_400_000)}
export function openAmount(invoice:ProfessionalInvoice,profile:BillingProfile,payments:Payment[]=[]){const paid=payments.filter(p=>p.invoiceId===invoice.id).reduce((sum,p)=>sum+(p.correction?-p.amount:p.amount),invoice.paidAmount);return Math.max(0,calculateBilling(invoice.lines,profile.fiscalScheme).total-paid)}
export function paymentSignal(invoice:ProfessionalInvoice,profile:BillingProfile,state:ReminderState={level:0},today="2026-09-22",payments:Payment[]=[]){const open=openAmount(invoice,profile,payments);const days=daysFromDue(invoice.dueDate,today);if(open<=0)return"Betaald";if(state.disputed)return"Betaling betwist";if(state.arrangement)return"Betalingsregeling";if(state.paused)return"Herinneringen gepauzeerd";if(invoice.status==="Concept")return"Concept";if(days>receivableSettings.dueSoonDays)return"Binnen betaaltermijn";if(days>0)return"Vervalt binnenkort";if(days===0)return"Vervalt vandaag";if(invoice.paidAmount>0)return"Betaling deels ontvangen";if(state.level>0)return"Herinnering verstuurd";return"Herinnering mogelijk"}
export function canSendReminder(invoice:ProfessionalInvoice,profile:BillingProfile,state:ReminderState={level:0},today="2026-09-22",payments:Payment[]=[]){if(["Concept","Betaald","Gecrediteerd","Geannuleerd","Definitief","Klaar voor verzending"].includes(invoice.status))return false;if(!invoice.sentAt||openAmount(invoice,profile,payments)<=0||daysFromDue(invoice.dueDate,today)>=0||state.disputed||state.arrangement||state.paused||state.pendingPayment)return false;if(state.lastSentAt&&Math.abs(daysFromDue(state.lastSentAt.slice(0,10),today))<receivableSettings.minimumReminderIntervalDays)return false;return true}
export function receivablesSummary(invoices:ProfessionalInvoice[],profile:BillingProfile,today="2026-09-22"){const open=invoices.filter(i=>!["Concept","Betaald","Gecrediteerd","Geannuleerd"].includes(i.status)).map(i=>({invoice:i,amount:openAmount(i,profile),days:daysFromDue(i.dueDate,today)})).filter(x=>x.amount>0);return{count:open.length,total:open.reduce((s,x)=>s+x.amount,0),withinTerm:open.filter(x=>x.days>receivableSettings.dueSoonDays).reduce((s,x)=>s+x.amount,0),dueSoon:open.filter(x=>x.days>=0&&x.days<=receivableSettings.dueSoonDays).reduce((s,x)=>s+x.amount,0),overdue:open.filter(x=>x.days<0).reduce((s,x)=>s+x.amount,0),overdueCount:open.filter(x=>x.days<0).length,oldest:open.filter(x=>x.days<0).sort((a,b)=>a.days-b.days)[0],reminders:open.filter(x=>canSendReminder(x.invoice,profile)).length}}
export function lockDueDate(invoiceDate:string,invoiceOverride:number|undefined,debtorDays:number|undefined,defaultDays:number){const date=day(invoiceDate);date.setDate(date.getDate()+(invoiceOverride??debtorDays??defaultDays));return date.toISOString().slice(0,10)}
