import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createServer } from './helpers/development-server.mjs';
import { PortalManagementService, customerRelationships, organizations, organizationFeatures, organizationChangeRequests, memberships, portalUsers, internalUsers, DEMO_ORGANIZATION_ID } from '../src/domain/portal-management-service.mjs';
import { auditLogs, tasks } from '../src/domain/demo-data.mjs';

const service=new PortalManagementService();

test('De Boer Advies is het enige volledige demo-profiel',()=>{const r=service.relationship('de-boer-advies');assert.equal(r.organizations.length,1);assert.equal(r.organizations[0].demoProfile,true)});
test('bestaande klant zonder uitgebreid profiel krijgt één-op-één compatibiliteitsrelatie',()=>{const r=service.relationship('studio-noord');assert.equal(r.organizations.length,1);assert.equal(r.organizations[0].legacyClientId,'studio-noord')});
test('er is precies één zichtbaar volledig demo-ondernemingsprofiel',()=>{const r=service.relationship('de-boer-advies');assert.equal(r.organizations.length,1);assert.equal(r.organizations[0].id,DEMO_ORGANIZATION_ID);assert.equal(organizations.filter(o=>o.demoProfile).length,1)});
test('personeel activeert personeel en loonadministratie',()=>{const org=service.organization('jansen-bouw');assert.equal(org.profile.staff,true);assert.equal(org.features.find(f=>f.module==='Loonadministratie').status,'Actief')});
test('wijzigingsverzoek wordt alleen op het demo-profiel verwerkt',()=>{const result=service.processChange('randy','change-staff-demo',{decision:'approve',effectiveAt:'2099-01-01',reason:'Demo akkoord'});assert.equal(result.organization.id,DEMO_ORGANIZATION_ID);assert.equal(result.organization.profile.employeeCount,1)});
test('historische taken blijven behouden na moduledeactivering',()=>{const before=tasks.length;service.setFeature('randy','jansen-bouw','Facturatie',{status:'Inactief',endsAt:'2026-12-31',reason:'Dienst beëindigd'});assert.equal(tasks.length,before);assert.equal(service.organization('jansen-bouw').features.find(f=>f.module==='Facturatie').status,'Inactief')});
test('klantwijzigingen verschijnen in centrale Office-werkvoorraad',()=>{assert.ok(service.workQueue().some(r=>r.relationship&&r.organization&&r.requester))});
test('portaalweergave gebruikt uitsluitend de demo-onderneming',()=>{const preview=service.preview('randy',DEMO_ORGANIZATION_ID);assert.equal(preview.organization.demoProfile,true);assert.ok(preview.activeModules.length>0)});
test('klantmedewerker ziet uitsluitend toegewezen ondernemingen',()=>{assert.equal(service.portalAccess('user-sanne-j','jansen-bouw').allowed,true);assert.equal(service.portalAccess('user-sanne-j','jansen-holding').allowed,false)});
test('rollen en rechten zijn voor de demo-onderneming vastgelegd',()=>{const user=service.relationship('de-boer-advies').users.find(u=>u.id==='user-jan');assert.equal(user.memberships.length,1);assert.equal(user.memberships[0].organizationId,DEMO_ORGANIZATION_ID);assert.equal(user.memberships[0].role,'Eigenaar')});
test('Office-medewerker zonder bevoegdheid kan fiscale module niet wijzigen',()=>{internalUsers.push({id:'viewer-test',name:'Viewer',role:'Alleen bekijken',status:'Actief',permissions:['organization.read']});assert.throws(()=>service.setFeature('viewer-test','jansen-bouw','Omzetbelasting',{status:'Inactief'}),/Onvoldoende bevoegdheid/);internalUsers.pop()});
test('manipulatie van organization_id levert geen toegang op',()=>{assert.deepEqual(service.portalAccess('user-sanne-j','jansen-vastgoed'),{allowed:false,reason:'NO_MEMBERSHIP'})});
test('geblokkeerde gebruiker verliest direct toegang',()=>{assert.deepEqual(service.portalAccess('user-blocked','jansen-bouw'),{allowed:false,reason:'ACCOUNT_BLOCKED'})});
test('laatste eigenaar kan niet worden verwijderd',()=>{assert.throws(()=>service.removeMembership('randy','m-demo-jan'),/laatste eigenaar/i)});
test('taakgeneratie veroorzaakt geen duplicaten',()=>{const first=service.generateTasks('jansen-bouw','2098-01-01','test'),second=service.generateTasks('jansen-bouw','2098-01-01','test');assert.ok(first.length>0);assert.equal(second.length,0)});
test('afwijzing past ondernemingsprofiel niet aan',()=>{organizationChangeRequests.push({id:'reject-test',customerRelationshipId:'rel-de-boer',organizationId:'de-boer-advies',requesterUserId:'user-jan',type:'Zakelijke auto aanschaffen',data:{},desiredEffectiveAt:'2028-01-01',receivedAt:'2026-09-21',ownerId:'ed',status:'Nieuw',missingInformation:[],impactedModules:['Voertuigen'],impactedTasks:[]});const before=service.organization('de-boer-advies').profile.vehicles;service.processChange('ed','reject-test',{decision:'reject',reason:'Niet van toepassing'});assert.equal(service.organization('de-boer-advies').profile.vehicles,before)});
test('audittrail registreert modulewijziging, verzoek en preview',()=>{assert.ok(auditLogs.some(a=>a.action==='Portaalmodule gewijzigd'));assert.ok(auditLogs.some(a=>a.action==='Klantverzoek verwerkt'));assert.ok(auditLogs.some(a=>a.action==='Portaalweergave geopend'))});
test('domeinreferenties zijn intern consistent',()=>{assert.ok(organizations.every(o=>customerRelationships.some(r=>r.id===o.customerRelationshipId)));assert.ok(organizationFeatures.every(f=>organizations.some(o=>o.id===f.organizationId)));assert.ok(memberships.every(m=>organizations.some(o=>o.id===m.organizationId)&&portalUsers.some(u=>u.id===m.userId)))});
test('mobiele en desktopcomponenten voor portaalbeheer zijn aanwezig',async()=>{const [js,css]=await Promise.all([readFile(new URL('../public/portal.js',import.meta.url),'utf8'),readFile(new URL('../public/styles.css',import.meta.url),'utf8')]);assert.match(js,/Portaalconfiguratie/);assert.match(js,/Portaalweergave/);assert.match(css,/@media\(max-width:800px\)/)});
test('API blokkeert ondernemingsdata zonder geldige Office-sessie',async t=>{const server=createServer().listen(0,'127.0.0.1');t.after(()=>server.close());await new Promise(resolve=>server.once('listening',resolve));const response=await fetch(`http://127.0.0.1:${server.address().port}/api/organizations/jansen-bouw`);assert.equal(response.status,401);const body=await response.json();assert.equal(body.ok,false)});
